#!/usr/bin/env python3
"""
Auto-discover Spotify playlists and populate playlists.txt.
Uses OAuth2 flow to fetch user's playlists without requiring API requests.

Usage:
    python update_playlists_txt.py
"""

import os
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
from spotify_sync.core.logger import Logger
from spotify_sync.utils.error_handler import ErrorHandler
from spotify_sync.utils.config import Config

# Load environment variables from .env file
load_dotenv()

SPOTIFY_CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET')
SPOTIFY_REDIRECT_URI = os.getenv('SPOTIFY_REDIRECT_URI', 'http://127.0.0.1:8888/callback')


def validate_credentials() -> None:
    """Validate that Spotify credentials are set."""
    if not SPOTIFY_CLIENT_ID or not SPOTIFY_CLIENT_SECRET:
        ErrorHandler.handle_fatal_exception(
            RuntimeError("Spotify credentials not found"),
            "Please create a .env file with SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET"
        )
        exit(1)


def get_user_playlists() -> list:
    """
    Authenticate and fetch user's playlists.
    
    Returns:
        List of playlists with name, id, and URL
    """
    Logger.info("Setting up OAuth flow...")
    
    auth_manager = SpotifyOAuth(
        client_id=SPOTIFY_CLIENT_ID,
        client_secret=SPOTIFY_CLIENT_SECRET,
        redirect_uri=SPOTIFY_REDIRECT_URI,
        scope='playlist-read-private playlist-read-collaborative',
        open_browser=False  # Don't try to open browser automatically
    )
    
    # Get the authorization URL
    auth_url = auth_manager.get_authorize_url()
    
    Logger.header("Spotify Authorization Required")
    Logger.info("Please open the following URL in your web browser:\n")
    print(f"  {auth_url}\n")
    Logger.info("After authorizing, you'll be redirected to a URL starting with:")
    print("  http://127.0.0.1:8888/callback?code=...\n")
    
    # Get the redirect URL from user
    redirect_url = input("Paste the full redirect URL here: ").strip()
    
    if not redirect_url:
        raise RuntimeError("No redirect URL provided")
    
    # Extract authorization code from redirect URL
    try:
        code = auth_manager.parse_response_code(redirect_url)
        token = auth_manager.get_access_token(code)
        Logger.success("Authorization successful!")
    except Exception as e:
        raise RuntimeError(f"Authorization failed: {e}")
    
    # Create Spotify client
    Logger.info("Fetching your playlists...")
    sp = spotipy.Spotify(auth_manager=auth_manager)
    
    # Fetch playlists
    playlists = []
    results = sp.current_user_playlists()
    
    while results:
        for item in results['items']:
            playlists.append({
                'name': item['name'],
                'id': item['id'],
                'url': item['external_urls']['spotify']
            })
        
        if results['next']:
            results = sp.next(results)
        else:
            results = None
    
    return playlists


def write_playlists_txt(playlists, filename="playlists.txt") -> None:
    """
    Write playlists to file in URL format.
    
    Args:
        playlists: List of playlist dictionaries
        filename: Output filename
    """
    try:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write("# Spotify Playlists\n")
            f.write("# Auto-generated by update_playlists_txt.py\n")
            f.write("# Lines starting with # are comments\n")
            f.write("# Each playlist URL should be on its own line\n\n")
            
            for pl in playlists:
                f.write(f"# {pl['name']}\n")
                f.write(f"{pl['url']}\n\n")
        
        Logger.success(f"Wrote {len(playlists)} playlists to {filename}")
    
    except Exception as e:
        ErrorHandler.handle_exception(e, f"Failed to write {filename}")
        raise


def main():
    """Main entry point for playlist discovery."""
    Logger.header("Spotify Playlist Discovery")
    
    try:
        validate_credentials()
        playlists = get_user_playlists()
        
        if not playlists:
            Logger.warning("No playlists found in your Spotify account")
            return
        
        Logger.success(f"Found {len(playlists)} playlist(s)")
        
        # Show playlists
        Logger.section("Your Playlists")
        for idx, pl in enumerate(playlists, 1):
            Logger.progress(idx, len(playlists), "playlists")
            print(f"  {pl['name']}")
        
        # Write to file
        Logger.info(f"\nWriting to playlists.txt...")
        write_playlists_txt(playlists)
        
        Logger.header("Done!")
        Logger.info("Next steps:")
        Logger.info("1. Edit playlists.txt if needed (optional)")
        Logger.info("2. Run: python src/check.py")
        
    except Exception as e:
        ErrorHandler.handle_fatal_exception(e, "Failed to discover playlists")
        exit(1)


if __name__ == "__main__":
    main()
